[project]
name = "ar-table-backend-service"
version = "0.1.0"

dependencies = [
    "numpy<2",
    "opencv-python==4.11.0.86",
    "websockets",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest]
minversion = "9.0"
addopts = ["-ra", "--import-mode=importlib"]
testpaths = ["tests"]
